runtime: java
env: flex

runtime_config:  # Optional
  jdk: openjdk8

manual_scaling:
  instances: 1
  
readiness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  app_start_timeout_sec: 2500
  
resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

service: api
