export const FOOD_WEIGHT = "FOOD_WEIGHT";
export const TRAFFIC_WEIGHT = "TRAFFIC_WEIGHT";
export const EDUCATION_WEIGHT = "EDUCATION_WEIGHT";

export const GET_ALL_ZIPCODES = "GET_ALL_ZIPCODES";
export const GET_TOP_ZIPCODES_BY_CATEGORY = "GET_TOP_ZIPCODES_BY_CATEGORY";
export const GET_ONE_ZIPCODE = "GET_ONE_ZIPCODE";
export const GET_FILTERED_ZIPCODES = "GET_FILTERED_ZIPCODE";

export const SIGN_IN = "SIGN_IN";
export const GET_USER_ZIPCODES = "GET_USER_ZIPCODES";
export const GET_USER_ZIPCODES_OBJECTS= "GET_USER_ZIPCODES_OBJECTS";

export const SIGN_OUT = "SIGN_OUT";